# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AXI_GPIO.xdc

# Block Designs: bd/AXI_GPIO/AXI_GPIO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_GPIO || ORIG_REF_NAME==AXI_GPIO} -quiet] -quiet

# IP: bd/AXI_GPIO/ip/AXI_GPIO_processing_system7_0_0/AXI_GPIO_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_GPIO_processing_system7_0_0 || ORIG_REF_NAME==AXI_GPIO_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_GPIO/ip/AXI_GPIO_axi_gpio_0_0/AXI_GPIO_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_GPIO_axi_gpio_0_0 || ORIG_REF_NAME==AXI_GPIO_axi_gpio_0_0} -quiet] -quiet

# IP: bd/AXI_GPIO/ip/AXI_GPIO_ps7_0_axi_periph_0/AXI_GPIO_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_GPIO_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_GPIO_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_GPIO/ip/AXI_GPIO_rst_ps7_0_50M_0/AXI_GPIO_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_GPIO_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_GPIO_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AXI_GPIO/ip/AXI_GPIO_auto_pc_0/AXI_GPIO_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_GPIO_auto_pc_0 || ORIG_REF_NAME==AXI_GPIO_auto_pc_0} -quiet] -quiet

# XDC: bd/AXI_GPIO/AXI_GPIO_ooc.xdc
